{% set name = "Iterative-HFold" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/conniexhe/Iterative-HFold.git

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
