{% set name = "Knotty" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
    git_url: https://github.com/hexinmao/knotty.git

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
